apiVersion: v1
kind: Pod
metadata:
  name: store-test
spec:
  containers:
    - name: store
      image: acontainers.azurecr.io/ratingsweb:v1
      ports:
        - containerPort: 80
          protocol: TCP
          name: http